from enum import Enum


class ImageType(Enum):
    """
    Image type
    """

    ANGRY = "angry"
    BAKA = "baka"
    BITE = "bite"
    BLUSH = "blush"
    BONK = "bonk"
    BORED = "bored"
    BULLY = "bully"
    BYE = "bye"
    CHASE = "chase"
    CHEER = "cheer"
    CRINGE = "cringe"
    CRY = "cry"
    CUDDLE = "cuddle"
    DAB = "dab"
    DANCE = "dance"
    DIE = "die"
    DISGUST = "disgust"
    FACEPALM = "facepalm"
    FEED = "feed"
    GLOMP = "glomp"
    HAPPY = "happy"
    HI = "hi"
    HIGHFIVE = "highfive"
    HOLD = "hold"
    HUG = "hug"
    KICK = "kick"
    KILL = "kill"
    KISS = "kiss"
    LAUGH = "laugh"
    LICK = "lick"
    LOVE = "love"
    LURK = "lurk"
    MIDFING = "midfing"
    NERVOUS = "nervous"
    NOM = "nom"
    NOPE = "nope"
    NUZZLE = "nuzzle"
    PANIC = "panic"
    PAT = "pat"
    PECK = "peck"
    POKE = "poke"
    POUT = "pout"
    PUNCH = "punch"
    RUN = "run"
    SAD = "sad"
    SHOOT = "shoot"
    SHRUG = "shrug"
    SIP = "sip"
    SLAP = "slap"
    SLEEPY = "sleepy"
    SMILE = "smile"
    SMUG = "smug"
    STAB = "stab"
    STARE = "stare"
    SUICIDE = "suicide"
    TEASE = "tease"
    THINK = "think"
    THUMBSUP = "thumbsup"
    TICKLE = "tickle"
    TRIGGERED = "triggered"
    WAG = "wag"
    WAGE = "wage"
    WINK = "wink"
    YES = "yes"
